### ISSUE TITLE
Best way to get transition out of conversation

### ISSUE THREAD

**Issue by brandonhilkert** [KartikTalwar/gmail.js#135]
Quick q, what's the best way to know that one has left a conversation view? Either gone back to the inbox, or clicked out of the threaded view by clicking one of the other labels or anything else really.

Thanks!

**Comment by KartikTalwar** [comment]
`gmail.check.is_inside_email()` but its not an observer. You'd have to do it via a setTimeout

**Comment by brandonhilkert** [comment]
I saw that and had the same thought. I'm more interested in getting it at the time they leave the conversation view, so I can resize some elements on the page. Any other ideas?

**Comment by KartikTalwar** [comment]
Yeah its hard to do that generically without inspecting the dom. If the person is not on preview panes, you'll know that they are not in an email thread if the navigator url changes. The url won't have the email hash. You can add a on hash change observer to your renderer. Otherwise, you'd have to either do setTimeout or attach a DOM observer and check if it changes. For example if the main view has an element with class `Cp` then its the inbox

**Comment by brandonhilkert** [comment]
I started going down that path. Observed that when in a conversation view, there's a `.g` element. You think `MutationObserver` or some jQuery event?

**Comment by KartikTalwar** [comment]
MutationObserver would definitely be better and simpler :-)
