### ISSUE TITLE
Set to: cc: bcc: on api.dom.compose object

### ISSUE THREAD

**Issue by lievenjanssen** [KartikTalwar/gmail.js#148]
In the code there is a comment on the to: cc: and bcc: fields (TODO: ability to set)

Are there any plans to implement the to: cc: bcc: in the near future?

**Comment by brentkelly** [comment]
@lievenjanssen - I had a brief look at this but didn't need it for my app so haven't implemented it yet.

It is more complex than the subject etc because it creates a bunch of DOM objects for each to/cc/bcc address to allow you to delete it with a click, drag it around etc. IIRC after a bunch of experimentation I found a hidden element that stored all to addresses, and that if you updated that & then clicked off it, gmail would add in all the DOM elements. So if that is correct then the best approach would be to update that field & then simulate a click. I had a bit of trouble simulating that click with jQuery but it looks like others have had more luck in other threads - can't remember the threads off the top of my head but I think they just used standard js to execute a mousedown followed by a mouseup?

Hope that helps.

**Comment by brentkelly** [comment]
@lievenjanssen - OK the mouse event thread I was referring to is #117 which seems to work fine for triggering the search.

I tried this approach here but it doesn't seem to work for me. I don't have much experience at simulating click events some perhaps someone knows more.

```javascript

// set email textarea field
$('textarea[name=to]').val('my@email.com');

// try to simulate a click on the subject input - doesn't work
var mouseUp = document.createEvent('MouseEvents');
mouseUp.initEvent( 'click', true, false );
$('input[name=subjectbox]')[0].dispatchEvent(mouseUp);

// try give focus to the subject input - doesn't work
$('input[name=subjectbox]').focus();
```

Aside from that approach, I'm sure really how you could implement this functionality without re-implementing the Gmail interface by recreate the entire DOM tree - including click & drag events - that Gmail creates when you add a to address. Unless Gmail is nice enough to apply those events automatically to all elements with a specific class name. I haven't tested that but I'd be very surprised, and even if it did, that would be some seriously brittle code :).

**Comment by glebovilya** [comment]
It seems like there have to be several places to add needed data - not only input[name="to"]. Probably solution is to add:

1) <div class="vR"><span class="vN vP a3q" email="email@email.com"><div class="vT">email@email.com</div><div class="vM"></div></span><input name="to" type="hidden" value="email@email.com"></div>

have to be added as previous sibling of textarea

2)<div id=":xx" class="oL aDm az9"><span email="email@email.com" class="aDr">email@email.com</span></div>

have to be added into form's second child div

Maybe I am wrong, but soultion with recipients field is not so easy and clear as adding a subject

**Comment by lievenjanssen** [comment]
@brentkelly currently I am setting the to and cc on the compose object I get back from the compose event like this:

```js
compose.$el.find('textarea[name=to]').val("to list");
compose.$el.find('textarea[name=cc]').val("cc list");
```

For me this is sufficient because when I click send the email gets send to the right addresses. I am not simulating any clicks.

Wondering if this implementation would suffice to implement the set functionality in the lib.

**Comment by glebovilya** [comment]
@lievenjanssen I think you should create a pull-request that contain this workarounds. It is a brilliant solution imo.

**Comment by onassar** [comment]
+1

**Comment by markon1** [comment]
These solutions don't work anymore, can someone point me to how set `bcc` of `compose`?

**Comment by josteink** [comment]
Are you saying that the `.to()`, `.cc()` and `.bcc()` methods on the compose-instance doesn't work?

**Comment by markon1** [comment]
@josteink not sure about `.to()` and `.cc()` since I don't use them, but `.bcc()` doesn't work as it should. When I click the `Bcc` in compose view, the address I set via `.bcc()` method is there, but it's plain text, it doesn't have that oval border around it, so when the email is sent, address I added via `.bcc()` method is disregarded.

**Comment by markon1** [comment]
@josteink I don't want to be annoying or anything :) , but I'm blocked by this issue and can't find a way around. Have you maybe had a chance to try and set `bcc`? Maybe you can provide me with an example as I see you're experienced with this library, maybe I'm missing something?

**Comment by josteink** [comment]
Sorry about the lack of response, but I've honestly been very, very busy with other things.

> When I click the Bcc in compose view, the address I set via .bcc() method is there, but it's plain text, it doesn't have that oval border around it, so when the email is sent, address I added via .bcc() method is disregarded.

Can confirm and can reproduce.

That said, this particular issue is not very important for the things I need Gmail.js for, so I probably won't be able to provide a production-hardened bug-fixo for this any time soon.

Despite that I've tested the viability of a workaround: simulating a keypress-event inside the textarea after setting the email. Using tab as the injected key-stroke, I get the expected behaviour.

It looks like this:

````javascript
// set value, normal way
let email = "demo@gmail.com";
compose.to(email);

// apply workaround
let el = compose.dom("to")[0];
let event = new KeyboardEvent("keydown", {
    bubbles : true,
    cancelable : true,
    key : "Tab",
    shiftKey : true,
    keyCode : 9
});

el.focus();
el.dispatchEvent(event);
````

Hopefully you can work with that to get the stuff you need working.

**Comment by josteink** [comment]
Oh bugger it. I've pushed a new version to npmjs.com (v1.0.2), and it has been updated to include this workaround.

Let me know if it works for you.

**Comment by markon1** [comment]
@josteink Thanks for your effort Jostein, but unfortunatelly it still doesn't work for me with v1.0.2, I experience the same thing as before, bcc is added but without that oval shape around it, and when email is sent bcc is not included.
Care to share a snippet of code with which you set the bcc of compose to some example email, just so I know I'm not missing something on my end?

**Comment by josteink** [comment]
To be honest, I never tested `bcc`. I only tested the `to` field, since they were all implemented pretty similarly.

Trying the same approach for `cc` and `bcc` I see it fails, and it seemingly does so because the fields are not shown when its value is being updated.

I've pushed yet another version (`1.0.3`) which force-shows the fields before updating the value. Hopefully that should solve your problems.

If not, can you confirm if the code to replace the `to`-field works or not? (So that we are sure that we are working on the right problem).

**Comment by markon1** [comment]
It works now, thank you very much!

**Comment by josteink** [comment]
Glad to hear that. Keeping this issue closed then :+1:

**Comment by lirikooda** [comment]
Wrapping up the current solution that worked for me:

```ts
type Field = 'cc' | 'bcc';

const KEYDOWN_EVENT = new KeyboardEvent("keydown", {
    bubbles: true,
    cancelable: true,
    key: "Tab",
    shiftKey: true,
    keyCode: 9
});

export const setRecipient = (compose: GmailDomCompose, field: Field, email: string) => {
    console.log("Setting recipient", field, email);

    compose.dom(`show_${field}`).trigger("click");

    const jqueryElement = compose.dom(field);

    jqueryElement.val(email);

    const htmlElement = jqueryElement[0];

    htmlElement.focus();
    htmlElement.dispatchEvent(KEYDOWN_EVENT);
}
```

**Comment by josteink** [comment]
Thanks! That looks good as a setter method!

I’d normally say the you could try to make a PR for it, but the existing method is supposed to be both a getter and setter. So not sure how that fits in that regard. 

Anyone have any opinions? 🙂

**Comment by ReallyLiri** [comment]
This solution stopped working for me, I think because of the `isTrusted` property of the event being `false`.

Instead, I'm just shifting the focuse after setting the value and it works well:

```ts
  const jqueryElement = compose.dom(field);

  jqueryElement.val(email);

  // focus on a different box so the injected field will get de-focused
  compose.dom('subjectbox')[0].focus()
```

**Comment by josteink** [comment]
Sounds like a PR to me? 🙂
