### ISSUE TITLE
gmail.get.email_data() not fetching email data correctly

### ISSUE THREAD

**Issue by grandhivamsi** [KartikTalwar/gmail.js#150]
Hi,

gmail.get.email_data() not fetching email data correctly if we have multiple threads. For one of the threads data not fetching properly.

For example I have an email with 4 threads. One of the email thread data is not coming correctly. Please look into this and do the needful.

Regards,
Vamsi

**Comment by KartikTalwar** [comment]
@grandhivamsi can you give more information please? can you paste screenshots of the thread screen and your json response for `get_data()` and pin point what the missing information is

**Comment by petsona** [comment]
gmail.get.email_data() failing for me as well. it uses ajax synchronous call which is deprecated, see jQuery documentation:

As of jQuery 1.8, the use of async: false with jqXHR ($.Deferred) is deprecated; you must use the success/error/complete callback options instead of the corresponding methods of the jqXHR object such as jqXHR.done() or the deprecated jqXHR.success().

**Comment by KartikTalwar** [comment]
@petsona for now, using an older version of jquery would be preferred but I'll try to making it async.

**Comment by KartikTalwar** [comment]
Async methods have now been added
