### ISSUE TITLE
hi, how get current dom compose in before sent_message action?

### ISSUE THREAD

**Issue by aghamohammadi** [KartikTalwar/gmail.js#221]
hi, how get current dom compose in before sent_message action?
i will get current dom compose in :

gmail.observe.before('send_message'function(url, body, data, xhr){

currentDomCompose= ????????

});

**Comment by brentkelly** [comment]
The send_message observer doesn't use the DOM to fire, so this method doesn't provide access to the DOM compose object. I haven't tested it, but chances are the DOM compose object has been destroyed by the time this observer fires.

The ``send_message`` observer fires when Gmail client side communicates with the server via ``XMLHttpRequest`` so ``before`` will fire directly prior to this request being sent.

If you wanting to manipulate the contents of the compose window when they click send, then this can be done by manipulating the ``xhr.xhrParams.body_params``. For example in certain circumstances I automatically bcc the email to an address by:

```javascript
			    var body_params = xhr.xhrParams.body_params;
				if (body_params.bcc) {
			      	if (typeof body_params.bcc !== 'object') {
			    		body_params.bcc = [ body_params.bcc ];
			      	}
			    } else {
			      body_params.bcc = [];
			    }
			    body_params.bcc.push(attach_address);
```

If however you are wanting to e.g. do some additional verification or something to the compose window before it gets to this point, then you will need to try & intercept a click to the 'send' button - something gmail.js doesn't currently do. One way of achieving this may be to observer ``gmail.observe.on('compose'...)`` and try detect a mouse click on the send button. I briefly tried playing around with this with limited success before concluding it was better off manipulating the XHR request behind the scenes anyway, rather than messing with the actual DOM.

Hope that helps.

**Comment by aghamohammadi** [comment]
thanks for reply

in realy i want to change body content befor sending email. i using this link https://github.com/KartikTalwar/gmail.js/issues/170 and change body content and too changed in console log  but after send dont change body content!
please help me!

this my source code : 


            var result ='my content';
            gmail.observe.before('send_message', function (url, body, data, xhr) {     
                 var oldCmml = xhr.xhrParams.url.cmml;
                   
                    var body_params = xhr.xhrParams.body_params;
                    
                    var new_element = '<div class="myclass"><div class="mycontent">' + result + '</div></div>';                                  

                    if (new_element.length > oldCmml) {
                        xhr.xhrParams.url.cmml = new_element.length;
                    } else {
                        new_element += '<div>';
                        while (new_element.length < oldCmml) {
                            new_element += ' ';
                        }
                        new_element += '</div>';
                        xhr.xhrParams.url.cmml = new_element.length;
                    }
                    
                    body_params.body = new_element;
                    console.log(oldCmml, xhr.xhrParams.url.cmml, body_params.body);
                    console.log("sending message, url:", url, 'body', body, 'email_data', data, 'xhr', xhr);
        });

**Comment by aghamohammadi** [comment]
for example, virtru extention 
how do you do this? first,finished processing then sending happen! 
by gmail.js is possible??
in realy many peaple want do this solution!

**Comment by brentkelly** [comment]
Reading through the other threads related to this issue, there is no point in updating the ``url.cmml`` parameter, as the URL has already been passed at this point.

If you want this functionality to work, you will need to either implement the ``before_open`` observer discussed in #90 into gmail.js, or try a similar solution to the one @keven425 used in that thread.

**Comment by josteink** [comment]
The best work-around I've found is probing for the "Email is sent toast". it contains the email-ID of the sent email.

Because this is an old issue, I'll close this for now, but please re-open and provide more details if you can still reproduce this.
