### ISSUE TITLE
Add new tab in the heading tablist

### ISSUE THREAD

**Issue by itsazzad** [KartikTalwar/gmail.js#224]
Is there any way to add new tab in the heading tablist out of the scope of the categories?
example: if I want to add a new tab named "Issues" and I want to write any html in that tabpanel.
Any hint would be a great help.
![screen shot 2016-01-05 at 4 38 16 am](https://cloud.githubusercontent.com/assets/54909/12102635/4bf7b970-b366-11e5-9a87-2570c008768d.png)

**Comment by KartikTalwar** [comment]
Unfortunately, this library intentionally does not contain many UI related functions because it is very hard to maintain with the constant changes in gmail. The best solution that I know to this is inspecting the elements and copying the html and inserting it in the dom.

So for this use-case, you would want to copy the `<td>` html and then use jquery to append that html into that table; something like

```
$('.aKk').append("<td>...</td>")
```

**Comment by josteink** [comment]
Because this is an old issue, I'll close this for now, but please re-open and provide more details if you can still reproduce this.
