### ISSUE TITLE
Can gmail.js become an npm package?

### ISSUE THREAD

**Issue by icem** [KartikTalwar/gmail.js#240]

**Comment by KartikTalwar** [comment]
It probably can. If the goal is to just have the latest version be available from npm then it can exist in the registry but since this isn't a node library and only works in chrome as a chrome extension, and has only 1 dependency, imo doesn't provide a great benefit to be on npm.

Is there a reason why you are curious?

**Comment by icem** [comment]
@KartikTalwar Yes the goal to have the latest version as npm dependency for easy update. I don't like the idea of copyting gmail.js to my extension code. Referencing it directly from github or your s3 is even worse idea. The only good solution is distribute via bower or npm. Also gmail.js could have dependency on jquery. https://github.com/jquery/jquery

**Comment by sommerwilken** [comment]
And it could be included more easily via module loader (import gmailjs from 'gmailjs'; or similar;
Right now, if importing as module, there are various issues with globals, i.e.: windows.opener

**Comment by icem** [comment]
:+1:
