### ISSUE TITLE
visible_emails thread limitations

### ISSUE THREAD

**Issue by joydesigner** [KartikTalwar/gmail.js#247]
Hi, 

gmail.get.visible_emails returns a maximum of 45 threads. Usually, gmail inbox view contains 50 emails per page.

Has anyone encountered similar issue? is there any workaround for this?

**Comment by joydesigner** [comment]
Fixed. the url param for the request for inbox currently is "mbox", for enterprise gmail inbox, it should be "inbox".

**Comment by josteink** [comment]
Sorry about the *extremely* slow response.

From what I can tell, you had an issue, and found a fix. Would you please consider submitting this fix as a PR? I promise I'll *personally* review it and I promise it won't take a year this time :)

Anyway, since there haven't been any activity since the time of filing, I'll assume this is no longer and issue and close it. If you still need something done, see you in that PR, ok? :)
