### ISSUE TITLE
view_email is only triggered once (not for each opened email in the thread)

### ISSUE THREAD

**Issue by lievenjanssen** [KartikTalwar/gmail.js#254]
When I open an email thread view_email is only triggered once while I would expect it to trigger for each opened email in the thread.

I guess this is due to the dom that is still loading because the dom element on view_thread doesn't contain all open emails immediately as well.

p.s. I am trying to add buttons in the email toolbar for each open email but when opening a large thread from the sent items not all buttons are inserted.

**Comment by ronoudgenoeg** [comment]
I am having the same issue. I need to add a button to each email currently visible, but view_email is only giving me the latest, and view_thread doesn't give me enough to go off and insert buttons on.

**Comment by brentkelly** [comment]
This is due to the way Gmail builds the DOM tree when initially opening a thread. It appears to initially build the whole thread on emails and then does one DOM insertion - so only 1 view_email action is observed even though there are other emails in the thread which may or may not be open. 

I guess the view_email default handler could be updated to check the inserted node for any matching email children nodes and them some kind or recursive call to view_email for each matching child. 

However,  the way I solved it was by simply doing this in my application view_email handler. I haven't got the code in front of me,  but IIRC it was basically a call to `.find` on the matching element passed to the handler looking for the normal class that identifies an individual email.

**Comment by lievenjanssen** [comment]
@brentkelly I solved it the same way in my code in the meantime. Think it would be good to fix this in the lib as well because it feels like a bug.

**Comment by ronoudgenoeg** [comment]
I solved it the same way as well, but agree it feels like a bug.

**Comment by dariospadoni** [comment]
Can I ask you exactly you solved it? I'm having the same issue here, thanks

**Comment by michi88** [comment]
You could maybe also add the button when they click on the email to open:
```javascript
    $('.kv').on('click', function () {
      // click on the email to expand (needed for hard page load on refresh)
      checkAttachments();
    });
```

**Comment by josteink** [comment]
Based on my experience this should work fine with the latest releases. Do you still have this issue?

If there's no response on this issue in the near future, I will assume all is now in order and close it.

**Comment by josteink** [comment]
If I re-read and try to understand the issue, view_email is actually only triggered once... ever... for a given single email. This I can confirm. This is a limitation in the API, and something you'll have to live with.

I've yet to encounter the issue with view_thread not triggering for all shown emails. If someone can find a way to reproduce that error consistently, please re-open this issue with more details and we'll look into it.

**Comment by josteink** [comment]
If I re-read and try to understand the issue, view_email is actually only triggered once... ever... for a given single email. This I can confirm. This is a limitation in the API, and something you'll have to live with. We might want to document this better though?

I've yet to encounter the issue with view_thread not triggering for all shown emails. If someone can find a way to reproduce that error consistently, please re-open this issue with more details and we'll look into it.
