### ISSUE TITLE
Any way to fetch user's Canned Email Responses?

### ISSUE THREAD

**Issue by markon1** [KartikTalwar/gmail.js#260]
Hi, I'm writing an Chrome Extension, and I'm looking to find a way to fetch all Canned Email Responses (it's an GMail feature that needs to be turned on through Settings>Labs and enables users to save predefined messages and then through compose window they can access them).

I couldn't find a method in your tool gmail.js, but I suppose someone could know a way around it maybe?

**Comment by josteink** [comment]
Sorry about the extremely slow response.

To answer your question: There might be, but I honestly don't think anyone on the core team will be working on it anytime soon.

Since I haven't heard anything new on this issue, I'm closing it. Please re-open it if you still have an issue you need resolved.
