### ISSUE TITLE
Issue in gmail.get.selected_emails_data() in pagination

### ISSUE THREAD

**Issue by mayurizingadeCL** [KartikTalwar/gmail.js#269]
Hello,

When I check any email from list, I am getting email details for first page correctly.

But Using pagination, when I am hitting older email button (">")to get older emails i.e. from 51:100, If I select 5th email from 51:100, I should get details of 55th email but I am getting details of 5th email i.e. email details of 5th email from first page though I am on older email page.

Please let me know the solution for it.

Thanks,
Mayuri Zingade

**Comment by josteink** [comment]
Sorry about the extremely slow response.

I've tested with various functions, and using `api.get.visible_emails()` I'm not able to reproduce this issue, so I'm guessing this has been fixed since the time of filing.

If you can still reproduce it, please re-open and show some example code, and we can try to figure it out together.

Again: Sorry about the slow response.
