### ISSUE TITLE
Gmail mbox always giving 144 records

### ISSUE THREAD

**Issue by mayurizingadeCL** [KartikTalwar/gmail.js#277]
Hello,

I want runtime list of emails from inbox(primary tab) using gmail.js.
I found below url is used to get list of emails in gmail.js.

"https://mail.google.com/mail/u/0/?ui=2&ik=6fdb4f9bc7&rid=undefined&at=AF6bupNbYX1fL4ns44UY0GRaG3PQOJ1Kmg&view=tl&rt=1&start=**0**&num=**50**&search=inbox"

For other folders when I am setting up start and num runtime, Its working fine.
But for inbox primary tab though I am setting anything in start and num, it its giving me first 144 records..

The issue is, There may be case when I need message from index 300 to 350.

Let me know what changes need to be done in url for that.

Thanks,
Mayuri Zingade

**Comment by mayurizingadeCL** [comment]
Please update the url in above issue as

"https://mail.google.com/mail/u/0/?ui=2&ik=6fdb4f9bc7&rid=undefined&at=AF6bupNbYX1fL4ns44UY0GRaG3PQOJ1Kmg&view=tl&rt=1&start=**0**&num=**50**&search=mbox"

**Comment by josteink** [comment]
Sorry about the extremely slow response.

Considering we haven't received any more input on this issue since you filed it, and considering you are doing things outside the Gmail.js API, I'm closing this one.

If you want to add any functionality to our API, please propose them through a pull request. I'll be happy to review it (and it wont take months, I promise!).
