### ISSUE TITLE
Bug with gmail.observe.after('send_message') in last gmail.js version

### ISSUE THREAD

**Issue by JerryBels** [KartikTalwar/gmail.js#343]
Hey guys,

I just upgraded gmail.js to the last version and something doesn't work anymore :(

I'm using 

    gmail.observe.after('send_message', function (url, body, data, xhr) {

In order to get thread_id and email_id and save them in my DB. Since I upgraded 1h ago, here is what I get : 

> gmail.js:904 Gmail post response parsing failed. SyntaxError: Unexpected string
>     at new Function (<anonymous>)
>     at Object.Gmail_.api.tools.parse_response (chrome-extension://pgplbgldgegboccmffplfjkfidfckdop/lib/providers/gmail/gmail.js:894:32)
>     at XMLHttpRequest.onreadystatechange (chrome-extension://pgplbgldgegboccmffplfjkfidfckdop/lib/providers/gmail/gmail.js:1006:57)

and returned xhr is empty. This doesn't occur in gmail.js API v5.

Thanks ahead for any help !

**Comment by josteink** [comment]
Thanks for the report. I'll take a look at it first thing tomorrow.

**Comment by josteink** [comment]
I've taken a brief look at this, and I'm partially able to reproduce. I do get a XHR object, but I also get the parsing-error as you've outlined.

Based on the stack-trace you've provided, there's seemingly only been one functional change in this function since 0.5, and that seems to be mine when I was cleaning up the formatting of the source:

https://github.com/KartikTalwar/gmail.js/commit/4ca09700863e228006bd9e8436423fe507ae2b13#diff-ed1a8db78264acfe07214717bdad5425L872

Ooops! Sorry about that!

Reverting that change fixes the parsing error for me.  I've searched the rest of the codebase for similar changes, but haven't found any other occurrences, so hopefully we should now be good.

You can see the changes here:
https://github.com/KartikTalwar/gmail.js/commit/ffe10fadc893d08344dcd5614241bc20fbf8d06f

I've pushed a new package on npmjs.org as well. Let me know if everything now works as it should for you.

**Comment by JerryBels** [comment]
Fixed indeed, thank you very much !
