### ISSUE TITLE
view_email only get maximum 5 emails

### ISSUE THREAD

**Issue by danieltigse** [KartikTalwar/gmail.js#346]
You can replicate this If you find for an email with a thread of more than 5 emails. If you find it and open it all the mails are displayed. The problem is that the lib only detect me 5 emails.

**Comment by josteink** [comment]
I'm having trouble reproducing this one.

Could you outline the steps needed to reproduce this error in more detail?

**Comment by danieltigse** [comment]
Sure.
1. Search for an email with a thread of more than 5 emails
2. Click on the suggestions that gmail give you when searching the email
3. If you put a log in the observer or debug in the line you will see that only detects 5 emails.

**Comment by josteink** [comment]
I guess I need to be more specific myself: Can you show me the code and functions you use which fail to detect more than 5 items? This is the part which is non-obvious to me.

**Comment by danieltigse** [comment]
Ok.

This is my code, it only prints the number of emails detected in the thread right?:
`gmail.observe.on('view_email', function(obj) {
		console.log(obj.id_element.length);
}`

So my test is that I search an email that has more than 5 mails in the thread like this:
<img width="854" alt="screen shot 2016-12-28 at 12 06 21 pm" src="https://cloud.githubusercontent.com/assets/1870723/21526990/2e675ff0-ccf6-11e6-8804-8378f9d7303a.png">

As you can see there are 8 emails in this thread.
<img width="980" alt="screen shot 2016-12-28 at 12 06 41 pm" src="https://cloud.githubusercontent.com/assets/1870723/21527003/3dfdbc20-ccf6-11e6-9211-a289120e2f21.png">

But in the log only prints 5
<img width="789" alt="screen shot 2016-12-28 at 12 07 01 pm" src="https://cloud.githubusercontent.com/assets/1870723/21527006/475fcf88-ccf6-11e6-925c-ea90b53898d3.png">

**Comment by josteink** [comment]
Any feedback on this? Is the workaround sufficient?

**Comment by danieltigse** [comment]
I tested the code but it doesn't work for me. First `obj.id` is undefined. When I try `gmail.get.email_data_async(obj.id_element[0].id, function(res)` or `gmail.get.email_data_async(obj.id, function(res)` I got undefined in the response.

**Comment by josteink** [comment]
> I tested the code but it doesn't work for me. First `obj.id` is undefined

That's extremely strange, and something I'm not able to reproduce. Strictly speaking it sounds like something which "shouldn't" be possible.

Can you, via debugger check if the codepath you're being taken to is this one?

https://github.com/KartikTalwar/gmail.js/blob/master/src/gmail.js#L2606-L2615

If so, at least we have a *slight* clue...

As for theories... Could it be performance-related? I've seen `gmail.js` DOM-events where we need to "wait it out" because we've intercepted the XHR and triggered the event before Gmail has actually updated the UI itself.

Maybe we need to wait some of our events out before we trigger them?

Could you inspect the state of `element` at this location in the code? Does `innerHTML` look what you would expect it to?

**Comment by josteink** [comment]
Old issue is old. Closing.
