### ISSUE TITLE
npm package import

### ISSUE THREAD

**Issue by gidsi** [KartikTalwar/gmail.js#347]
Having a problem with the npm package.

If im trying this:
```
import GmailFactory from 'gmail-js';

const Gmail = GmailFactory.Gmail();

Gmail.observe.on('open_email', function(arg1) {
	console.log(arg1);
	console.log(Gmail.get.email_data(arg1));
});

Gmail.observe.on('load', () => {
	console.log('loaded');
        console.log(Gmail.get.user_email());
}
```

Gives me a "loaded" and undefined log, the other listener isn't firing at all when i'm browsing around.

Is it a bug or am i doing something horribly wrong? Is it supposed to work that way?

**Comment by KartikTalwar** [comment]
hey @gidsi could you give this a try with the example chrome extension and see if you get the same error? https://github.com/KartikTalwar/gmail-chrome-extension-boilerplate

**Comment by josteink** [comment]
I'm not able to reproduce this at all. I'm using TypeScript though.

My TypeScript code looks like this:

````typescript
import * as jQuery from "jquery";
const $ = jQuery;
import "gmail-js";
const gmail = new Gmail($);
````

Transpiled into Javascript it looks like this:

````javascript
const jQuery = require("jquery");
const $ = jQuery;
require("gmail-js");
const gmail = new Gmail($);
````

That loads and works perfectly for me, with absolutely zero issues. I wonder why you're getting a different behaviour...

Note: I'm using browserify to package my extension, via gulp and a pretty big pipeline, but I don't think there's anything there which should alter the fundamentals... Looking at the final dist-compiled JS, it all looks the same.

What happens if you use `var GmailFactory = require("gmail-js")` instead of that `import`?

If that works, we should probably document it better :)

**Comment by josteink** [comment]
Any news on this?

If no feedback is received soon, this issue will be closed assuming everything works as it should (especially since it works for me in all my use-cases :).

**Comment by gidsi** [comment]
We're still on it (it didn't work out with require). Right now we're too busy with other stuff, we will be back on this in approx. two weeks.
But it's maybe a problem with webpack, in doubt just close it :)

**Comment by josteink** [comment]
I'll consider that feedback for now. Just don't want to keep open issues around if nobody cares about them :)

**Comment by gidsi** [comment]
Looks like we were doing something horribly wrong, we had all the stuff in the content script of a chrome extension, which does provide access to the window object but not to window.GLOBALS.
http://stackoverflow.com/questions/20499994/access-window-variable-from-content-script

Maybe we could add a warning log there or something giving a hint on that issue if globals isn't accessible, but i don't know right now where to put it :/

**Comment by josteink** [comment]
Not something I'll prioritize right now,but glad you worked it out :)
