### ISSUE TITLE
How to insert HTML file to for new window in Gmail

### ISSUE THREAD

**Issue by zvikae** [KartikTalwar/gmail.js#349]
Hi.

I'd like to add new window modal when after user login to gmail.
How can I insert html file into gmail code?
Till now, I created elements document.createElement("div") and then appendChild.

Is there another way simply add html file without creating each div etc.?
I tried `<link rel="import" href="test.html">`
but gmail think that it's: https://mail.google.com/mail/u/0.test.html..

In addition, how can I add css file? 
I tried to do: 
`var link = '<link rel="stylesheet" type="text/css" href="' + fileName + '">'`
` $('head').append(link)`
And get the same error as before.

Thanks!

**Comment by josteink** [comment]
This is really outside the scope of this library.

You should use whatever you would otherwise use to provide HTML and application/dialog like functionality.

It could be a templating library (jQuery template, underscore, etc) or a full blown GUI framework like React or Angular.

Gmail.js just gives you a place to deliver the payload. A payload provided by a better suited library. And that's it.

For more information and details on this, I would search the web for general resources on how to develop front-end components in HTML/JS and maybe additionally in web-extensions.

Closing issue as it's not really related to gmail.js. Sorry :)
