### ISSUE TITLE
How do I call this from background.js?

### ISSUE THREAD

**Issue by ConnGator** [KartikTalwar/gmail.js#351]
I used the boilerplate code to implement this and I know it is loading correctly as it calls gmail.get.user_email() fine. However, I want to do something when the icon is clicked. I added a background.js that has chrome.browserAction.onClicked.addListener and it gets called but I cannot access the gmail object.

Do I have to enable something for this? Am somewhat new to extensions so I feel like I am missing a step.

Thanks for any tips or pointers.

**Comment by josteink** [comment]
You'll have to use cross-context window messaging to do this, because the only place where the `Gmail` object is available is in the browser-context where GMail is loaded.

Use can use `window.postMessage()` and related event-listeners to implement this.

**Comment by josteink** [comment]
Short answer: You can't.

You'll have to use cross-context window messaging to do this, because the only place where the `Gmail` object is available is in the browser-context where GMail is loaded. You cannot use gmail.js in any other context.

To get around this use `window.postMessage()` and related event-listeners to get messages and commands into browser-context where you can use the Gmail API.

**Comment by kstubs** [comment]
It's been 3 years and Chrome has come a long ways, yet I am still unable to listen to a chrome runtime message sent from my embed code integrating gmail.js.  Is this still the case, in order to communicate with my background script and/or popup script, I must rely on window.posMessage() to do so?  Just clarifying since chrome does offer an onMessageExternal event listener.

Based on my understanding of sending and listening to an external message with chrome runtime, I am having no luck.

Karl..

**Comment by josteink** [comment]
You most post message from browser context to content script context.

In context-script context you must repost to background script.

**Comment by kstubs** [comment]
By chance is there a working example of this or boiler plate?  I'm trying
to populate my popup with current email details, like Subject, To/From
addresses etc..

Karl..

Karl Stubsjoen
(602) 845-0006

**Comment by josteink** [comment]
Sorry. No. 

That’s more “generic” WebExtensions material and checking Stack Overflow, MDN and similar sites will probably yield you better results.
