### ISSUE TITLE
gmail.observe.on('open_email', function (emailId) {} Error

### ISSUE THREAD

**Issue by BUNKER74** [KartikTalwar/gmail.js#389]
Hello!
Error when open mail with draft - **api.dom.email called with invalid element/id**

`gmail.observe.on('open_email', function (emailId) {
            email = new gmail.dom.email(emailId);
}`

**Comment by josteink** [comment]
You get this error because you're using the API incorrectly. See the following example:

````javascript
gmail.observe.on("open_email", console.log);
// click email
> Object {ui: "2", ik: "4b86ba4469", view: "ad", th: "15aae17848143dda", pws: "1"…}  XMLHttpRequest {xhrParams: Object, readyState: 1, timeout: 0, withCredentials: false, onreadystatechange: function…}
````

The value provided to your function at this point is NOT the email-id. Also, are you certain you're not looking for the `view_email` event?

This will contain a proper `gmail.dom.email`-object which is handled and documented for you.

````javascript
// required to trigger sub-observer view_email
gmail.observe.on("view_thread", function(){}); 
gmail.observe.on("view_email", console.log);
// click email
> Gmail_.api.dom.email {id_element: jQuery.fn.init(1), id: "159d4b359feccaf2", $el: jQuery.fn.init(1)}
````

**Comment by BUNKER74** [comment]
view_email event does not work for me...

**Comment by josteink** [comment]
Did you also subscribe to view_thread event as instructed in the example above ?

**Comment by BUNKER74** [comment]
Ooops...
Did not pay proper attention to this line. It works fine. Thanks!
