### ISSUE TITLE
Multiple initialisation of my gmail gadget 

### ISSUE THREAD

**Issue by bb-swapnil** [KartikTalwar/gmail.js#399]
Hi Team, 

Gmail.js works excellent. I have a very minor issue which is whenever I open an email a single button should appear as below:-
<img width="1162" alt="screen shot 2017-05-18 at 1 59 25 pm" src="https://cloud.githubusercontent.com/assets/24839893/26193705/b1b06900-3bd3-11e7-88d1-18e36c359c85.png">

Now when I click the right arrow and immediately click the left arrow, I see two buttons as below:-
<img width="1172" alt="screen shot 2017-05-18 at 2 15 57 pm" src="https://cloud.githubusercontent.com/assets/24839893/26194001/8f38171e-3bd4-11e7-8574-849ab33d3f45.png">
 
I have written the following code to initialise gmail.js:-
`var main = function(){ `
`gmail = new Gmail();  `
`gmail.observe.on("load", function(){$("#gmailJsModalWindowOk").hide();`
`        $("#gmailJsModalWindowCancel").hide();`
`       $("#order_search").hide();`
`        newToolBar();`
`    });`
`};`

Where am I going wrong ?

**Comment by josteink** [comment]
Without knowing how and when `main()` get's called, it's hard to tell. It definitely looks like this code is getting run twice though.

The first thing I'd do would be to add some logging, which preferably should also [include a stacktrace](http://stackoverflow.com/a/635852), so that you can see when and how your code is called.

If this code is getting called twice, the problem is in how you wire up `main()`, and not in `gmail.js`.

**Comment by bb-swapnil** [comment]
Hey thanks for the lead, I got it fixed by a small hack 
`if(document.getElementById('my_id')==null){ //button appear}else{//do nothing}`

Will continue testing this again and post issues if found. I am closing the ticket.
