### ISSUE TITLE
gmail.observe.on NOT working

### ISSUE THREAD

**Issue by steelx** [KartikTalwar/gmail.js#411]
Hi,

the observe event doesnt return anything.

`gmail.observe.on("open_email", console.log);`
Also, i get follow error as well.

`var emailObject = gmail.dom.email('15d6ae2829399efe');`
**gmail.js:1 api.dom.email called with invalid element/id**

```
gmail.observe.on("load", function () {
        alert('this works');

       // below doesn't
      gmail.observe.on("open_email", console.log);
});
```

Kindly revert.

**Comment by steelx** [comment]
Fixed this by using the https://github.com/KartikTalwar/gmail-chrome-extension-boilerplate loader method. Now Gmail.js is executing after everything is loaded.

`refresh(init);`

**Comment by josteink** [comment]
My preliminary guess is that something related to [this commit](https://github.com/KartikTalwar/gmail.js/commit/54ab61932d5522421b7535c10b6a303b97ac3a43) has caused [some DOM validation-code](https://github.com/KartikTalwar/gmail.js/blob/master/src/gmail.js#L2696) to no longer be accurate.

Based on that I have the following question:

* Does the emailObject-code still work with the different loading?
* Are you testing under similar conditions? (inline vs popped up reply)

Any feedback on this issue is appreciated :)

**Comment by josteink** [comment]
In lack of feedback, and considering issue was reported resolved, I’m closing this one.
