### ISSUE TITLE
chrome identity is not accessible from main.js

### ISSUE THREAD

**Issue by Debolinap** [KartikTalwar/gmail.js#509]
I am using gmail.js boilerplate example. I am integrating google api with this. I am unable to access chrome identity from main.js. 
In manifest.json

````json
  "permissions": [
    "identity",
    "identity.email",
    "http://*/",
    "https://*/",
    "management",
    "storage",
    "tabs"
],
````
in main.js

````javascript
chrome.identity.getAuthToken({
    interactive: true
  }, handleAuthResult);
````
the identity is not accessible from main.js

though identity is accessible from background.js.

I have 2 questions,
1. Is there any way to access chrome.identity from main.js? If yes, how to do that
2. I have added gmail.tools.add_toolbar_button() in my code and on click on this button I want to make a call to a method in background.js. How to do that.
I tried with the following code
in main.js

````javascript
  chrome.runtime.sendMessage(extension_id, {message: "hi"}, (response) => {
    console.log(response.message);
  });
````
In background.js
````
chrome.runtime.onMessage.addListener(
  (request, sender, sendResponse) => {
    if (request.message === "hi") {
    console.log('message: hi to You')
      sendResponse({message: "hi to you"});
    }
  });
````

But It's not working. Control is not getting to background

Thanks in advance.

**Comment by josteink** [comment]
Hey there.

> I am using gmail.js boilerplate example

First off? Which boilerplate project? [This one](https://github.com/josteink/gmailjs-node-boilerplate) is the one which is recommended to ensure fewest problems.

> Is there any way to access chrome.identity from main.js? If yes, how to do that

The `chrome`-object is not and never will be available in the main extension code. This is because this code is running in a normal web-page context.

If you want to access the `chrome`-object, this will have to happen in a WebExtension-context. That means you will need to do it in either the content-page or the background-page.

> I have added gmail.tools.add_toolbar_button() in my code and on click on this button I want to make a call to a method in background.js. How to do that.
>
> I tried with the following code in main.js

While your observations are correct, you seem make a few mistakes. But all in all you have the right idea: you need to resort to message-passing.

Since chrome isn't available in the main browser-context, you will have to send messages using the `window.postMessage()`. Conversely in your content-script you will have to use `window.addEventListener("message", ...)`.

If you want to pass this further along to your background-page, you can now (in your content-script) use 
`chrome.runtime.sendMessage()`.

It's a bit of a chore, but that's how WebExtensions works.

Hope this helps.

**Comment by josteink** [comment]
Since this is *technically* a WebExtension-question and not a Gmail.js question I'm closing this issue. If you need more help, please check other WebExtension/JS-specific resources, like Stack Overflow.

**Comment by Debolinap** [comment]
Thanks for the confirmation
