### ISSUE TITLE
Support for Inbox UI

### ISSUE THREAD

**Issue by luka2i** [KartikTalwar/gmail.js#515]
Hey, anyone has any insights whether the inbox.google.com will be compatible with gmail.js?

**Comment by josteink** [comment]
This is not supported and none of the active contributors are working on it.

Also worth noting, based on how you read Google's PR-statements, it sounds like Inbox was a prototype/playground for ideas for new Gmail, and that new Gmail will get more of Inbox's features eventually rather than the  other way around.

And that sounds awfully close to Inbox having a retirement date. As such, putting in effort to support Inbox is not very appealing.

Technically speaking, under the hood, Inbox also shares no similarities with gmail (w.r.t DOM layout, selectors, XHR format, etc) so supporting this would involve a complete from scratch implementation... All while we maintain compatibility with existing gmail.js code.

Especially considering the ongoing, prioritized work to ensure better support for *New Gmail*, expecting any support for Inbox any time soon is not very realistic.

Unless, ofcourse, someone else does all that work and sends us a PR for this.
