### ISSUE TITLE
selected_emails_data() is returning wrong mails when inbox type is priority inbox 

### ISSUE THREAD

**Issue by Debolinap** [KartikTalwar/gmail.js#528]
selected_emails_data() is returning wrong mail data when inbox type is anything else then default.
For example, if the inbox type is selected as priority inbox, and I am selecting the 5th mail from the inbox (mails are sorted as priority), selected_emails_data() is returning the mail data of 5th mail from default view which is a different mail from the selected one.

**Comment by josteink** [comment]
I believe this is a known bug, and a PR[1] was actually started to address it. Unfortunately the PR kinda stalled, and the issue is still unresolved.

Feel free to take a look at the code and the existing PR and see if there's any way you can help out.

[1] https://github.com/KartikTalwar/gmail.js/pull/489

**Comment by Debolinap** [comment]
@josteink ,
 visible mail information are fetch using a get ajax call to the url. url is created based on window location, label etc.
I want to change implementation of this url creation logic so that the get call to the url returns mail information depending on inbox type and categories(social/ promotion etc). But I am not sure what are the other path params the url takes. Is there any doc provided by google? for inbox type anything other that default how to modify the query, what should I provide in search path param.

**Comment by SudarsananS** [comment]
@josteink @KartikTalwar 
Please help on this issue as this is critical for us as Debolina stated.We are getting wrong emails selected
when we have Inbox type selected anything other than default.

**Comment by josteink** [comment]
> Please help on this issue as this is critical for us

Seeing as that may be, this is a free open-source library driven entirely by unpaid contributors, fixing the parts which they depend on.

This bug is not a priority for me, nor do I suspect for @KartikTalwar. If you want this fixed, you will have to consider becoming a contributor. Debug it, create a patch and send in a PR (or continue the work of PR #489).

> Is there any doc provided by google describing what are the query params it takes, what are the values are expected for this params ?

No. It's all reverse-engineered. If you need this fixed, you will have to do some more reverse-engineering and find out what goes where.

Once you have a patch/PR though, I will be happy to review and test.

**Comment by Debolinap** [comment]
@josteink ,
I resolved this issue. I added a new method in gmail.js that parse the gmail dom and find the mails which are selected (aria-label="true"). 
following is the newly created method. It returns thread Id, last message Id (if conversation mode is off it is the message id). I tested this method in new gmail view for all inbox type and categories. It worked fine. Though this solution doesn't work for old gmail ui. I don't see the message ID and thread ID information in the gmail DOM.
  
    api.get.get_all_selected_mails = function () {        
        let selectedMailData=[];
        $('table.F.cf.zt tr').each(function() {
            // console.log('checkbox value', $(this).find('td.oZ-x3.xY div.oZ-jc.T-Jo.J-J5-Ji').attr('aria-checked'));
            if( $(this).find('td.oZ-x3.xY div.oZ-jc.T-Jo.J-J5-Ji').attr('aria-checked')=== 'true') {
                targetMailData= $(this).find('td.xY.a4W span[data-legacy-thread-id]');
                console.log('target mail data', targetMailData);
                selectedMailData.push({
                    messageId: targetMailData.attr('data-legacy-last-message-id'),
                    threadId: targetMailData.attr("data-legacy-thread-id"),
                    subject: targetMailData.text()
                })
            }
        }
        )
    console.log('Selected mails by parsing dom', selectedMailData);
    return selectedMailData;
    }

Please review. 
P.S I don't have permission to create a branch or raise a PR to this repository.

**Comment by josteink** [comment]
First of all: Sorry about the slow response.

> I resolved this issue

That's great news!

>  I added a new method 

Would it be possible to instead patch up the old one to work properly instead of creating a new one? That is, the fix doesn't leave old broken code behind?

>  parse the gmail dom and find the mails which are selected (aria-label="true").

Lately Google seem to have been adding more "integration-friendly" HTML with regard to attributes and 
stuff like that.

So if that works, that sounds like a good enough approach for me, and I have no issue relying on that.

Judging by your solution, and the existing bug-reports, it would seem that the existing does many of the same things as your code deoes, with the exception of pulling in email-data using `api.get.visible_emails()`:

https://github.com/KartikTalwar/gmail.js/blob/578afc2c1eb97649d18c43478d51b0e03b6dec3b/src/gmail.js#L2163-L2172

`api.get.visible_emails()` again seems to depend on XHR (which is getting increasingly problematic), and which I suspect is the root-cause of this:

https://github.com/KartikTalwar/gmail.js/blob/578afc2c1eb97649d18c43478d51b0e03b6dec3b/src/gmail.js#L2142-L2148

So... From what I can tell, you've actually a method we never had before (`api.get.selected_email_ids()`) which avoids the bugs we have in our existing code.

Would it be possible to combine this new method with `api.get.email_data()` in a way to get a functional re-implementation of our existing method `api.get.selected_emails_data()`?

If not, I guess this method is still useful and I'm inclined to accept it.

>  I tested this method in new gmail view for all inbox type and categories. It worked fine. 

Great!

> Though this solution doesn't work for old gmail ui. I don't see the message ID and thread ID information in the gmail DOM.

I can confirm this. These attributes are only available in the message-view of the old Gmail.

That means that if we end up trying to patch the existing code, we will need to branch out using and `if (api.check.is_new_gui()) {` to switch the code between new and old Gmail.

Which brings us to...

> Please review.

It will need some review. And the best way to do that is to raise a PR.

> I don't have permission to create a branch or raise a PR to this repository.

You don't need permission to create a PR. But you need to click the "fork" button first to create your own forked gmail.js repo. In that forked repo you can create a branch and commit your patches.

After you have done that, Github will let you create a PR from your repo back to mainline gmail.js.

Sounds good? Can you give that a try?

**Comment by SimonBiggs** [comment]
Hi @josteink and @Debolinap,

Did there ever end up being a PR to make a new API for "selected_emails_data" that doesn't rely on the deprecated Gmail API?

If not, is this a PR that you would be open to receiving if I were to write it?

Also, would a new `selected_emails_data` need to handle "new vs old" GUI checks any longer?

**Comment by josteink** [comment]
> Did there ever end up being a PR to make a new API for selected_emails_data that doesn't rely on the deprecated Gmail API?

Don't think so, to be honest. PRs are always welcome :)

**Comment by SimonBiggs** [comment]
Kk awesome. Do I need to retain backwards compatibility for that API given that now that function doesn't work any longer?

**Comment by josteink** [comment]
Don't fix/replace that API-call in place. Create a new one in the `gmail.new.get.*` namespace.

**Comment by josteink** [comment]
Old issue is old. Closing.
