### ISSUE TITLE
open_email no longer registers if the email is read

### ISSUE THREAD

**Issue by endriuska** [KartikTalwar/gmail.js#529]
Since about 2 weeks ago we cannot catch the event when the email is opened. It works with UNREAD emails, however if the email is read - it does not work. we are using open_email

https://www.screencast.com/t/L27FWeUd
https://www.screencast.com/t/kfecwdcT
https://www.screencast.com/t/4Kp08jYM

Any ideas? we haven't made any changes. Thanks

**Comment by josteink** [comment]
Just to be clear, as to my understanding, Gmail now exists in three "versions":

| Version      | api.check.is_new_data_layer() | api.check.is_new_gui() |
|--------------|-------------------------------|------------------------|
| Classic      | false                         | false                  |
| Transitional | true                          | false                  |
| New          | true                          | true                   |

Some of the events Gmail.js responds to are so called XHR-eventes which relies on the data-layer. That means you may now be on the new data layer without any visible changes, but still affected by underlying changes.

Are you certain these changes in behaviour you are reporting applies to the same "version" of Gmail?

If this error is w.r.t. the new data-layer, you can see this is a known issue::
https://github.com/KartikTalwar/gmail.js/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+new+gmail+in%3Atitle

The fix for that is sending patches :)

**Comment by josteink** [comment]
Old issue is old. Closing.
