### ISSUE TITLE
Events and almost all functions are not working

### ISSUE THREAD

**Issue by kevinpiac** [KartikTalwar/gmail.js#599]
Hey guys, 

Thanks for this library. I just wanted to know the current lib status? Is it supposed to work? 
I have the following issues (non-exhaustive list): 

- impossible to observe send_message neither using 'after', 'on' nor 'before'. 
- impossible to get the user's email... 

However the "load events and the .dom. methods seem to work fine.

Here is some commented code sample:

```js
gmail.observe.on('load', () => {
  console.log('Loaded') // WORKS 
  gmail.get.user_email(); // UNDEFINED

  gmail.observe.on("send_message", function(url, body, data, xhr) {
     console.log('Something') // NEVER TRIGGERED
  })
  gmail.observe.before('send_message', function (url, body, data, xhr) {
    console.log('Something') // NEVER TRIGGERED
  });
  gmail.observe.after('send_message', function (url, body, data, xhr) {
    console.log('Something') // NEVER TRIGGERED
  });
  gmail.observe.on('http_event', function(e){
    console.log('Something') // NEVER TRIGGERED
  });

  gmail.dom.toolbar().append(myElement) // WORKS
  ........
});
```

Do you have any info/tips which could help? Am I missing something or is the library down?

Thanks :)

**Comment by josteink** [comment]
It's a mixed bag.

Most stuff used to work fine before, but then new Gmail came along and changed pretty much all the non-DOM foundations of the library.

The result is that for new Gmail (which we can assume a majority of users are on, except a few enterprise Gsuite-users), data- and event-support is pretty much limited to what Gmail.js has received PRs for.

`send_message` in particular is tricky, because google doesn't actually *send* the email immediately in new Gmail, because of the the new "undo send" feature.

But it *should* work, or else a production extension I have right is broken :smile:

**Comment by kevinpiac** [comment]
Ok thanks a lot for your reply @josteink ! :) 
I'll try to investigate on this path then.
