### ISSUE TITLE
Gmail.js usage in practice blocking my access to Gmail.

### ISSUE THREAD

**Issue by Hewlbern** [KartikTalwar/gmail.js#602]
As above. 

This is after using the boilerplate code provided in this readme, with an updated gmail.js file of course, and also when following https://cloud.google.com/blog/products/gcp/deepbreath-preventing-angry-emails-with-machine-learning ,

Love to get around this issue!

Thanks in advance,

**Comment by josteink** [comment]
Honestly not sure what your issue is. 

Can you describe it in more detail? What exactly do you do? What exact kind of failures does this lead to? Are these failures associated with your Google-account, or just Gmail? Are these effects in place only when your extension runs, or always?

Etc etc.

Without more info, it's hard to provide any help.

**Comment by Hewlbern** [comment]
Thanks Josteink,

Basically when the extension is on Gmail will have a fault and not load.
I believe it's associated with Gmail and not my Google account. It just happens when I access Gmail.

I have set permissions for all urls.

I will test to see if I remove the all permission if it will work, but should work I think regardless?

**Comment by josteink** [comment]
Providing some errors from the web-console log or extension log might help too.

**Comment by Hewlbern** [comment]
chrome-extension://bkbcbhlhlbcpipcngadknaapjphobocg/third_party/gmail.js:7 Uncaught SyntaxError: 

Unexpected token '<'

m=b:820 Uncaught M0acause: ReferenceError: Gmail is not defined

    at eval (eval at sDa (https://mail.google.com/_/scs/mail-static/_/js/k=gmail.main.en.Na36fYVoAuY.O/am=X9PPQXhA8BL4sjMCGIAYjEo57OH_pBTomxyWB8BDjGgA-h2gDwAAAAAAAAAAAAAAAAAAAPZAYyU/d=1/im=1/dg=0/ct=zgms/rs=AHGWq9DaIYS1s-1SA3rudy6d3KzekU9HtQ/m=b:142:87), <anonymous>:12:3)
    at refresh (chrome-extension://bkbcbhlhlbcpipcngadknaapjphobocg/main.js:10:5)
    at eval (eval at sDa (https://mail.google.com/_/scs/mail-static/_/js/k=gmail.main.en.Na36fYVoAuY.O/am=X9PPQXhA8BL4sjMCGIAYjEo57OH_pBTomxyWB8BDjGgA-h2gDwAAAAAAAAAAAAAAAAAAAPZAYyU/d=1/im=1/dg=0/ct=zgms/rs=AHGWq9DaIYS1s-1SA3rudy6d3KzekU9HtQ/m=b:142:87), <anonymous>:1:1)
    at eval (<anonymous>)
    at sDa (https://mail.google.com/_/scs/mail-static/_/js/k=gmail.main.en.Na36fYVoAuY.O/am=X9PPQXhA8BL4sjMCGIAYjEo57OH_pBTomxyWB8BDjGgA-h2gDwAAAAAAAAAAAAAAAAAAAPZAYyU/d=1/im=1/dg=0/ct=zgms/rs=AHGWq9DaIYS1s-1SA3rudy6d3KzekU9HtQ/m=b:142:87)
    at https://mail.google.com/_/scs/mail-static/_/js/k=gmail.main.en.Na36fYVoAuY.O/am=X9PPQXhA8BL4sjMCGIAYjEo57OH_pBTomxyWB8BDjGgA-h2gDwAAAAAAAAAAAAAAAAAAAPZAYyU/d=1/im=1/dg=0/ct=zgms/rs=AHGWq9DaIYS1s-1SA3rudy6d3KzekU9HtQ/m=b:141:269
    at d (https://mail.google.com/_/scs/mail-static/_/js/k=gmail.main.en.Na36fYVoAuY.O/am=X9PPQXhA8BL4sjMCGIAYjEo57OH_pBTomxyWB8BDjGgA-h2gDwAAAAAAAAAAAAAAAAAAAPZAYyU/d=1/im=1/dg=0/ct=zgms/rs=AHGWq9DaIYS1s-1SA3rudy6d3KzekU9HtQ/m=b:820:137)message: "Error in protected function: Gmail is not defined"stack: "ReferenceError: Gmail is not defined↵    at eval (eval at sDa (https://mail.google.com/_/scs/mail-static/_/js/k=gmail.main.en.Na36fYVoAuY.O/am=X9PPQXhA8BL4sjMCGIAYjEo57OH_pBTomxyWB8BDjGgA-h2gDwAAAAAAAAAAAAAAAAAAAPZAYyU/d=1/im=1/dg=0/ct=zgms/rs=AHGWq9DaIYS1s-1SA3rudy6d3KzekU9HtQ/m=b:142:87), <anonymous>:12:3)↵    at refresh (chrome-extension://bkbcbhlhlbcpipcngadknaapjphobocg/main.js:10:5)↵    at eval (eval at sDa (https://mail.google.com/_/scs/mail-static/_/js/k=gmail.main.en.Na36fYVoAuY.O/am=X9PPQXhA8BL4sjMCGIAYjEo57OH_pBTomxyWB8BDjGgA-h2gDwAAAAAAAAAAAAAAAAAAAPZAYyU/d=1/im=1/dg=0/ct=zgms/rs=AHGWq9DaIYS1s-1SA3rudy6d3KzekU9HtQ/m=b:142:87), <anonymous>:1:1)↵    at eval (<anonymous>)↵    at sDa (https://mail.google.com/_/scs/mail-static/_/js/k=gmail.main.en.Na36fYVoAuY.O/am=X9PPQXhA8BL4sjMCGIAYjEo57OH_pBTomxyWB8BDjGgA-h2gDwAAAAAAAAAAAAAAAAAAAPZAYyU/d=1/im=1/dg=0/ct=zgms/rs=AHGWq9DaIYS1s-1SA3rudy6d3KzekU9HtQ/m=b:142:87)↵    at https://mail.google.com/_/scs/mail-static/_/js/k=gmail.main.en.Na36fYVoAuY.O/am=X9PPQXhA8BL4sjMCGIAYjEo57OH_pBTomxyWB8BDjGgA-h2gDwAAAAAAAAAAAAAAAAAAAPZAYyU/d=1/im=1/dg=0/ct=zgms/rs=AHGWq9DaIYS1s-1SA3rudy6d3KzekU9HtQ/m=b:141:269↵    at d (https://mail.google.com/_/scs/mail-static/_/js/k=gmail.main.en.Na36fYVoAuY.O/am=X9PPQXhA8BL4sjMCGIAYjEo57OH_pBTomxyWB8BDjGgA-h2gDwAAAAAAAAAAAAAAAAAAAPZAYyU/d=1/im=1/dg=0/ct=zgms/rs=AHGWq9DaIYS1s-1SA3rudy6d3KzekU9HtQ/m=b:820:137)"__proto__: Cq
(index):86 Uncaught (in promise) Error: A
    at ld.i ((index):86)
    at m=a:1056
    at (index):127
    at d (m=b:820)
m=b:820 Uncaught M0a {message: "Error in protected function: t`a6jdv`2", cause: Error: t`a6jdv`2
    at https://mail.google.com/mail/u/1/:78:130
    at d (https://mail.google.com/…, stack: "Error: t`a6jdv`2↵    at https://mail.google.com/ma…)↵    at https://mail.google.com/mail/u/1/:78:517"}

**Comment by Hewlbern** [comment]
Specifically this one is the issue I believe

Uncaught 
M0a
cause: ReferenceError: Gmail is not defined at eval (eval at sDa (https://mail.google.com/_/scs/mail-static/_/js/k=gmail.main.en.Na36fYVoAuY.O/am=X9PPQXhA8BL4sjMCGIAYjEo57OH_pBTomxyWB8BDlGgA-h2gDwAAAAAAAAAAAAAAAAAAAPZAYyU/d=1/im=1/dg=0/ct=zgms/rs=AHGWq9BLSGBh3cRoHlfMl6801wcnu2e1Rg/m=b:142:87), <anonymous>:12:3) at refresh (chrome-extension://bkbcbhlhlbcpipcngadknaapjphobocg/main.js:10:5) at eval (eval at sDa (https://mail.google.com/_/scs/mail-static/_/js/k=gmail.main.en.Na36fYVoAuY.O/am=X9PPQXhA8BL4sjMCGIAYjEo57OH_pBTomxyWB8BDlGgA-h2gDwAAAAAAAAAAAAAAAAAAAPZAYyU/d=1/im=1/dg=0/ct=zgms/rs=AHGWq9BLSGBh3cRoHlfMl6801wcnu2e1Rg/m=b:142:87), <anonymous>:1:1) at eval (<anonymous>) at sDa (https://mail.google.com/_/scs/mail-static/_/js/k=gmail.main.en.Na36fYVoAuY.O/am=X9PPQXhA8BL4sjMCGIAYjEo57OH_pBTomxyWB8BDlGgA-h2gDwAAAAAAAAAAAAAAAAAAAPZAYyU/d=1/im=1/dg=0/ct=zgms/rs=AHGWq9BLSGBh3cRoHlfMl6801wcnu2e1Rg/m=b:142:87) at https://mail.google.com/_/scs/mail-static/_/js/k=gmail.main.en.Na36fYVoAuY.O/am=X9PPQXhA8BL4sjMCGIAYjEo57OH_pBTomxyWB8BDlGgA-h2gDwAAAAAAAAAAAAAAAAAAAPZAYyU/d=1/im=1/dg=0/ct=zgms/rs=AHGWq9BLSGBh3cRoHlfMl6801wcnu2e1Rg/m=b:141:269 at d (https://mail.google.com/_/scs/mail-static/_/js/k=gmail.main.en.Na36fYVoAuY.O/am=X9PPQXhA8BL4sjMCGIAYjEo57OH_pBTomxyWB8BDlGgA-h2gDwAAAAAAAAAAAAAAAAAAAPZAYyU/d=1/im=1/dg=0/ct=zgms/rs=AHGWq9BLSGBh3cRoHlfMl6801wcnu2e1Rg/m=b:820:137)
message: "Gmail is not defined"
stack: "ReferenceError: Gmail is not defined↵    at eval (eval at sDa (https://mail.google.com/_/scs/mail-static/_/js/k=gmail.main.en.Na36fYVoAuY.O/am=X9PPQXhA8BL4sjMCGIAYjEo57OH_pBTomxyWB8BDlGgA-h2gDwAAAAAAAAAAAAAAAAAAAPZAYyU/d=1/im=1/dg=0/ct=zgms/rs=AHGWq9BLSGBh3cRoHlfMl6801wcnu2e1Rg/m=b:142:87), <anonymous>:12:3)↵    at refresh (chrome-extension://bkbcbhlhlbcpipcngadknaapjphobocg/main.js:10:5)↵    at eval (eval at sDa (https://mail.google.com/_/scs/mail-static/_/js/k=gmail.main.en.Na36fYVoAuY.O/am=X9PPQXhA8BL4sjMCGIAYjEo57OH_pBTomxyWB8BDlGgA-h2gDwAAAAAAAAAAAAAAAAAAAPZAYyU/d=1/im=1/dg=0/ct=zgms/rs=AHGWq9BLSGBh3cRoHlfMl6801wcnu2e1Rg/m=b:142:87), <anonymous>:1:1)↵    at eval (<anonymous>)↵    at sDa (https://mail.google.com/_/scs/mail-static/_/js/k=gmail.main.en.Na36fYVoAuY.O/am=X9PPQXhA8BL4sjMCGIAYjEo57OH_pBTomxyWB8BDlGgA-h2gDwAAAAAAAAAAAAAAAAAAAPZAYyU/d=1/im=1/dg=0/ct=zgms/rs=AHGWq9BLSGBh3cRoHlfMl6801wcnu2e1Rg/m=b:142:87)↵    at https://mail.google.com/_/scs/mail-static/_/js/k=gmail.main.en.Na36fYVoAuY.O/am=X9PPQXhA8BL4sjMCGIAYjEo57OH_pBTomxyWB8BDlGgA-h2gDwAAAAAAAAAAAAAAAAAAAPZAYyU/d=1/im=1/dg=0/ct=zgms/rs=AHGWq9BLSGBh3cRoHlfMl6801wcnu2e1Rg/m=b:141:269↵    at d (https://mail.google.com/_/scs/mail-static/_/js/k=gmail.main.en.Na36fYVoAuY.O/am=X9PPQXhA8BL4sjMCGIAYjEo57OH_pBTomxyWB8BDlGgA-h2gDwAAAAAAAAAAAAAAAAAAAPZAYyU/d=1/im=1/dg=0/ct=zgms/rs=AHGWq9BLSGBh3cRoHlfMl6801wcnu2e1Rg/m=b:820:137)"
__proto__: Error
message: "Error in protected function: Gmail is not defined"
stack: "ReferenceError: Gmail is not defined↵    at eval (eval at sDa (https://mail.google.com/_/scs/mail-static/_/js/k=gmail.main.en.Na36fYVoAuY.O/am=X9PPQXhA8BL4sjMCGIAYjEo57OH_pBTomxyWB8BDlGgA-h2gDwAAAAAAAAAAAAAAAAAAAPZAYyU/d=1/im=1/dg=0/ct=zgms/rs=AHGWq9BLSGBh3cRoHlfMl6801wcnu2e1Rg/m=b:142:87), <anonymous>:12:3)↵    at refresh (chrome-extension://bkbcbhlhlbcpipcngadknaapjphobocg/main.js:10:5)↵    at eval (eval at sDa (https://mail.google.com/_/scs/mail-static/_/js/k=gmail.main.en.Na36fYVoAuY.O/am=X9PPQXhA8BL4sjMCGIAYjEo57OH_pBTomxyWB8BDlGgA-h2gDwAAAAAAAAAAAAAAAAAAAPZAYyU/d=1/im=1/dg=0/ct=zgms/rs=AHGWq9BLSGBh3cRoHlfMl6801wcnu2e1Rg/m=b:142:87), <anonymous>:1:1)↵    at eval (<anonymous>)↵    at sDa (https://mail.google.com/_/scs/mail-static/_/js/k=gmail.main.en.Na36fYVoAuY.O/am=X9PPQXhA8BL4sjMCGIAYjEo57OH_pBTomxyWB8BDlGgA-h2gDwAAAAAAAAAAAAAAAAAAAPZAYyU/d=1/im=1/dg=0/ct=zgms/rs=AHGWq9BLSGBh3cRoHlfMl6801wcnu2e1Rg/m=b:142:87)↵    at https://mail.google.com/_/scs/mail-static/_/js/k=gmail.main.en.Na36fYVoAuY.O/am=X9PPQXhA8BL4sjMCGIAYjEo57OH_pBTomxyWB8BDlGgA-h2gDwAAAAAAAAAAAAAAAAAAAPZAYyU/d=1/im=1/dg=0/ct=zgms/rs=AHGWq9BLSGBh3cRoHlfMl6801wcnu2e1Rg/m=b:141:269↵    at d (https://mail.google.com/_/scs/mail-static/_/js/k=gmail.main.en.Na36fYVoAuY.O/am=X9PPQXhA8BL4sjMCGIAYjEo57OH_pBTomxyWB8BDlGgA-h2gDwAAAAAAAAAAAAAAAAAAAPZAYyU/d=1/im=1/dg=0/ct=zgms/rs=AHGWq9BLSGBh3cRoHlfMl6801wcnu2e1Rg/m=b:820:137)"
__proto__: Cq
constructor: ƒ (b)
__proto__: Error

**Comment by josteink** [comment]
Then Gmailjs is not loaded properly. That’s an extension-error on your part, not errorvwith Gmailjs. 

Please retry creating your extension or a minimal proof of concept for your bug using the boilerplate project linked in README.md. If that works, you need to take it from there. 

Please also read the _full_ README for the boilerplate project too, to avoid common errors. 

Also avoid using code-minification. It’s absolutely wasted on extensions (since they are only downloaded once and run inside the browser already) and they make stacktraces (like yours) useless for debugging.

**Comment by Hewlbern** [comment]
thanks man!

**Comment by Hewlbern** [comment]
Okay so I found the source of that issue. Now I've copied the boilerplate code exactly, and I am getting a separate error, although the console is displaying Hello, {email}.

The Gmail.js error is,

gmail.js:40 GmailJS: Unable to access window.opener! DOMException: Blocked a frame with origin "https://mail.google.com" from accessing a cross-origin frame.
    at new Gmail (chrome-extension://nbhcfnjohbadbaecebjgoahllglbaipo/third_party/gmail.js:34:47)
    at eval (eval at FDa (https://mail.google.com/_/scs/mail-static/_/js/k=gmail.main.en.CUZQN1zWnWo.O/am=X9PPQXhA8BL4sjMCCEAMRqUc9vB_Ugr0mRyWB8BDjGgA-h2gDwAAAAAAAAAAAAAAAAAAAPaAxko/d=1/im=1/dg=0/ct=zgms/rs=AHGWq9CqZhsMOMKxbyc9-J9SE6-GokAz6Q/m=b:142:87), <anonymous>:4:11)
    at refresh (chrome-extension://nbhcfnjohbadbaecebjgoahllglbaipo/main.js:8:5)
    at eval (eval at FDa (https://mail.google.com/_/scs/mail-static/_/js/k=gmail.main.en.CUZQN1zWnWo.O/am=X9PPQXhA8BL4sjMCCEAMRqUc9vB_Ugr0mRyWB8BDjGgA-h2gDwAAAAAAAAAAAAAAAAAAAPaAxko/d=1/im=1/dg=0/ct=zgms/rs=AHGWq9CqZhsMOMKxbyc9-J9SE6-GokAz6Q/m=b:142:87), <anonymous>:1:1)
    at eval (<anonymous>)
    at FDa (https://mail.google.com/_/scs/mail-static/_/js/k=gmail.main.en.CUZQN1zWnWo.O/am=X9PPQXhA8BL4sjMCCEAMRqUc9vB_Ugr0mRyWB8BDjGgA-h2gDwAAAAAAAAAAAAAAAAAAAPaAxko/d=1/im=1/dg=0/ct=zgms/rs=AHGWq9CqZhsMOMKxbyc9-J9SE6-GokAz6Q/m=b:142:87)
    at https://mail.google.com/_/scs/mail-static/_/js/k=gmail.main.en.CUZQN1zWnWo.O/am=X9PPQXhA8BL4sjMCCEAMRqUc9vB_Ugr0mRyWB8BDjGgA-h2gDwAAAAAAAAAAAAAAAAAAAPaAxko/d=1/im=1/dg=0/ct=zgms/rs=AHGWq9CqZhsMOMKxbyc9-J9SE6-GokAz6Q/m=b:141:269
    at d (https://mail.google.com/_/scs/mail-static/_/js/k=gmail.main.en.CUZQN1zWnWo.O/am=X9PPQXhA8BL4sjMCCEAMRqUc9vB_Ugr0mRyWB8BDjGgA-h2gDwAAAAAAAAAAAAAAAAAAAPaAxko/d=1/im=1/dg=0/ct=zgms/rs=AHGWq9CqZhsMOMKxbyc9-J9SE6-GokAz6Q/m=b:820:137),



Content Server Web Browser Extension: not applicable for href='https://accounts.google.com/o/oauth2/postmessageRelay?parent=https%3A%2F%2Fmail.google.com&jsh=m%3B%2F_%2Fscs%2Fabc-static%2F_%2Fjs%2Fk%3Dgapi.gapi.en.Sj5LKyeUKoE.O%2Fd%3D1%2Fct%3Dzgms%2Frs%3DAHpOoo9ToCtoaz0mr9IKXAop6Eq9AIpSlw%2Fm%3D__features__#rpctoken=594498241&forcesecure=1'; 

And 

m=B5zbye,RI4GO,UZdBGe,VOAugd,YesRdb,hif4bd,jGPO6,kL0rjf,lUPpNd,mE4mJ,saV8oc,u7EXMd:144 Failed to execute 'postMessage' on 'DOMWindow': The target origin provided ('https://hangouts.google.com') does not match the recipient window's origin ('https://mail.google.com').

**Comment by josteink** [comment]
So allow me to clarify:

* Have you used the boilerplate project exactly as is? The `refresh()` call seems to imply something other custom code is going on.
* If email-lookup is working, is other operations working too, like `gmail.new.get.email_data()`?
* Apart from errors in your console, are there any actual function you are trying to use which is causing failure?

Can you show me a minimal repo (based on boilerplate) to repro this error?

**Comment by slepmog** [comment]
> Have you used the boilerplate project exactly as is? The refresh() call seems to imply something other custom code is going on.

The `refresh()` call is specifically from the boilerplate project, https://github.com/KartikTalwar/gmail-chrome-extension-boilerplate/blob/master/main.js, that is officially mentioned from https://github.com/KartikTalwar/gmail.js/tree/master#using-gmailjs.

I have tried using it, and I have tried replacing it with better alternatives, and they all show result in problem.

gmail.js appears to create a race condition that in about 50% of cases prevents the gmail interface from finishing loading.  
The envelope with the big red M appears, the red line below it fills, and when it comes to about 95%, it stops, and in the console appear two events:

> (2) Failed to detect interface load in 10 seconds. Will automatically fire event in 5 further seconds.  
> gmail.js:2166

> Uncaught (in promise) Error: E
    at (index):94

Then the loading progress bar hangs and never resumes.

When the race condition does not happen, it loads instantly.

Because the gmail interface is pretty much a single page app, the `load` event is triggered way before the interface is actually there, and if gmail.js tries to examine it too early, it does something that prevents the interface from loading.

> Apart from errors in your console, are there any actual function you are trying to use which is causing failure?

No, instantiating `gmail = new Gmail();` is enough.

Although, the first of the two errors mentioned above only happens if you subscribe to the `load` event. If you don't, only the `Error: E` appears, but the interface still hangs and does not load.

So the mere instantiation of gmail.js breaks it (with 50% probability).

If you only inject the script files into the gmail page, but don't instantiate gmail.js, then the interface loads instantly at all times without errors.

**Comment by josteink** [comment]
> The refresh() call is specifically from the boilerplate project, https://github.com/KartikTalwar/gmail-chrome-extension-boilerplate/blob/master/main.js, that is officially mentioned from https://github.com/KartikTalwar/gmail.js/tree/master#using-gmailjs.
>
> I have tried using it, and I have tried replacing it with better alternatives, and they all result in the same problem.

That boilerplate project is obsolete and no longer supported/maintained, and a known cause of bugs and issues.

In short: don’t use it. 

Use this instead: https://github.com/josteink/gmailjs-node-boilerplate

**Comment by slepmog** [comment]
> Use this instead: https://github.com/josteink/gmailjs-node-boilerplate

Not being an expert, I couldn't figure out how to use that template provided that we don't use/don't want to use nodejs.
There is already [a corresponding issue](https://github.com/josteink/gmailjs-node-boilerplate/issues/13) opened against that template too, so I'm pretty sure both templates demonstrate it, and therefore it's not necessarily about the template.

An observation I just made:
When the interface hangs while loading, the `window.load` event always fires exactly twice.
When it fires exactly once, everything loads normally.

gmail.js does not appear to support this, and even if you detect, from your `window.load` handler, that you're handling the second event, and exit without doing anything, the entire thing still hangs.

The entire `main.js` looks like this:

```js
"use strict";

var gmail;

function main() {
    console.log("Main called");

    if (gmail !== undefined) {
        console.log("Second instance, exiting");

        return;
    }

    gmail = new Gmail();
    gmail.observe.on("load", () => {
        gmail.observe.on("view_email", (domEmail) => { });
    });
}

console.log("The js file is being executed");

(function ($) {    
    console.log("Entered $ closure");
    $(window).one("load", main);
    console.log("Exiting $ closure");
})(jQuery);
```

When the issue happens, I see:

![image](https://user-images.githubusercontent.com/7415007/79238631-4a8ab100-7e78-11ea-8fa9-b85d9034ad58.png)

When everything is fine, it's

![image](https://user-images.githubusercontent.com/7415007/79238877-950c2d80-7e78-11ea-9e7b-fc64e1f571d3.png)

I'm using `$(window).one("load");` because of all the events, it's the latest. `document.ready` and `document.load` occur earlier, and if I bind to them, it is almost 100% guarantee that the interface will hang while loading, even though in this case there will be only one `Main called` in the console.

**Comment by josteink** [comment]
> Not being an expert, I couldn't figure out how to use that template provided that we don't use/don't want to use nodejs.

Consider it a requirement from now on. You can't reliably get gmail.js to load early enough in Gmail's loading phase using any other way.

> There is already a corresponding issue opened against that template too, so I'm pretty sure both templates demonstrate it, and therefore it's not necessarily about the template.

It may not be about that template, but then at least we are debugging loading-issues as experienced in the only way which is actually currently supported to load Gmail.JS.

> When the interface hangs while loading, the window.load event always fires exactly twice.
When it fires exactly once, everything loads normally.

Good digging. That sounds really interesting. I have no idea what would cause that. Could it be an incompatibility with any other extensions you have?

If you can reproduce this with the (clean) Node boilerplate example, I'd love to see the stack trace you get for that. I might be able to work with that.
