### ISSUE TITLE
gmail.dom.email(id).attachments() returns incorrect urls

### ISSUE THREAD

**Issue by emilmuller** [KartikTalwar/gmail.js#613]
In my Gmail, gmail.dom.email(id).attachments() returns an array where all the urls are set to "https://mail.google.com/mail/u/0/https".

Not sure if I'm doing anything wrong?

I did copy gmail.js directly from the repository though (not through npm).

**Comment by josteink** [comment]
In general using `gmail.dom.email().attachments()` is not recommended, since it doesn't work reliably across browsers. (Google only sets it for Chrome).

Instead you should use the much more reliable data-API, which has this set at `gmail.new.data.email_data().attachments`:

https://github.com/KartikTalwar/gmail.js#gmailnewgetemail_dataidentifier

**Comment by erikplatou** [comment]
@emilmuller

**Comment by emilmuller** [comment]
@josteink Thanks! I was able to get it working :)
