### ISSUE TITLE
api.check.is_new_data_layer()

### ISSUE THREAD

**Issue by enric-joco** [KartikTalwar/gmail.js#619]
I was thinking is api.check.is_new_data_layer() still necessary, or we can suppose gmail is working always as a new_data_layer, now?

**Comment by josteink** [comment]
You can obviously decide on what you want to support in your extension, but as my extension is a commercial one where we have paying customers, we want to ensure everything is working for everyone.

So obviously we're reporting telemetry on this, and don't ask me how, because I really don't know, but 10% of our customers are still using "old" gmail somehow.

In our case, putting in the extra effort to make sure those 10% users are happy is not that big an effort and worth it for us. For you... You'll have to decide yourself.

**Comment by enric-joco** [comment]
I really thought that was deprecated :( .Now I have another question. How do you test the "old" gmail version?

**Comment by josteink** [comment]
The truth is that we can't, so we just don't change those bits (in our code or in gmailjs) which interact with the "old" gmail codebase, and hope things keeps working as it should.

**Comment by enric-joco** [comment]
ok, great to know. Thanks!!
