### ISSUE TITLE
Missing: gmail.dom .compose()

### ISSUE THREAD

**Issue by yellowandy** [KartikTalwar/gmail.js#89]
Great job so far on this api, thank you!  Noticed that gmail.dom .compose() seems to be missing in the master branch?  I was looking for a way to programmatically pop open the compose screen and hopefully specify the subject,body, and recipients.  Thanks for your help!

**Comment by lievenjanssen** [comment]
@brentkelly  this doesn't seem to work for me when I do ```compose.subject("test")``` on the compose object I get back from ```gmail.observe.on('compose'....)``` it's not doing anything.

**Comment by brentkelly** [comment]
@lievenjanssen I've just tested this & think I know what is going wrong for you. The code works fine, but it's a matter of execution order - I'm guessing you are probably trying to set the field before the field has been successfully injected into the DOM.

As a general rule of thumb, unless there is a good reason why not, I defer the execution of all code when an event gets triggered. So your solution here is something like this:

```gmail.observe.on('compose', function(compose,type) { 
	window.setTimeout(function(){
		compose.subject('THIS IS A TEST');
	},0);
});```

For more info about deferring code check out [_.defer's docs](http://underscorejs.org/#defer), or the first reply to [this thread here](http://stackoverflow.com/questions/15489163/why-does-underscore-defer-fix-so-many-of-my-issues)

@KartikTalwar - one thing we could do to avoid these (usually confusing) issues is to always defer the execution of a function bound to a DOM observer? Or at least by default. Basically this means that by default you wouldn't be able to execute your code the moment the relevant DIV is inserted - but it will always wait until the current call stack has finished executing (inserting all nodes into the DOM relevant to that event). I can't think of any use cases off the top of my head where this would break someone's code so it's probably a good modification. Do you have any thoughts there?

**Comment by lievenjanssen** [comment]
@brentkelly @KartikTalwar I already thought it was because the field was not injected in the DOM yet but I expected it to work without the need to defer it so I think  always deferring may be a good fix.

**Comment by lievenjanssen** [comment]
@brentkelly I also need to be able to fill out the to: and cc: fields do you have any idea when this will be available? If it's not too hard I would be glad to check it out myself if you give me some pointers.

**Comment by brentkelly** [comment]
@lievenjanssen - I had a brief look at this but didn't need it for my app so haven't implemented it yet.

It is more complex than the subject etc because it creates a bunch of DOM objects for each to/cc/bcc address to allow you to delete it with a click, drag it around etc. IIRC after a bunch of experimentation I found a hidden element that stored all to addresses, and that if you updated that & then clicked off it, gmail would add in all the DOM elements. So if that is correct then the best approach would be to update that field & then simulate a click. I had a bit of trouble simulating that click with jQuery but it looks like others have had more luck in other threads - can't remember the threads off the top of my head but I think they just used standard js to execute a mousedown followed by a mouseup?

Hope that helps.
